services:
  - type: web
    name: django-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput || true
    startCommand: |
      python manage.py migrate --noinput && \
      python manage.py ensure_superuser && \
      daphne -b 0.0.0.0 -p $PORT app.asgi:application
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: app-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "0"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: PYTHONUNBUFFERED
        value: "1"

databases:
  - name: app-db
    plan: free
