services:
  - type: web
    name: django-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput || true
    startCommand: |
      # Attente DB + migrations (5 tentatives, 5s d'intervalle)
      for i in 1 2 3 4 5; do
        python manage.py migrate --noinput && break
        echo "DB pas prête, on retente dans 5s... ($i/5)"
        sleep 5
      done
      # Création admin (n'empêche pas le boot si ça échoue)
      python manage.py ensure_superuser || true
      # Lancer le serveur ASGI
      daphne -b 0.0.0.0 -p $PORT app.asgi:application
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: app-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "0"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: PYTHONUNBUFFERED
        value: "1"

databases:
  - name: app-db
    plan: free
